# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: alloc-init
description: blog for @WestonHanners
email: admin@alloc-init.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alloc-init.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: WestonHanners
github_username:  westonhanners
encoding: utf-8
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate-v2

author:
  twitter: westonhanners
  
feed:
  path: feed

exclude: 
  - devmode
  - prepare
  - compile
  - vendor
  - README.md
  - Gemfile*

pagination:
  enabled: true
  debug: true
  per_page: 5
  permalink: '/page/:num/'
  collection: 'posts'
  sort_reverse: true
  trail: 
    before: 2
    after: 2

sass:
  sass_dir: _sass   
  style: compressed


permalink: /blog/:year.:month.:day