title: alloc-init
description: blog for @WestonHanners
email: admin@alloc-init.com
baseurl: ""
url: "https://alloc-init.com"
twitter_username: WestonHanners
github_username:  westonhanners
encoding: utf-8
paginate: 5
paginate_path: "/page/:num/"

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-paginate

author:
  picture: /images/me.jpeg
  twitter: WestonHanners

feed:
  path: feed

exclude: 
  - vendor
  - README.md
  - Gemfile*

collections:
  posts:
    permalink: /blog/:year.:month.:day
    output: true
  rpg:
    permalink: /rpg/:title
    output: true

sass:
  sass_dir: _sass   
  style: compressed