#!/bin/bash
echo "*** Fixing Files..."
find . -type f -exec chmod 644 {} \; 
echo "*** Fixing Directories..."
find . -type d -exec chmod 755 {} \;
echo "*** Fixing PhileCMS"
chmod -R 777 content lib/cache lib/datastorage
echo "*** Fixing Fix Permissions..."
chmod +x fixpermissions
