#!/bin/bash
echo "*** Fixing script permissions..."
chmod +x prepare
chmod +x compile
chmod +x devmode
echo "*** Building..."
./compile
echo "*** Fixing Files..."
find ../alloc -type f -exec chmod 644 {} \; 
echo "*** Fixing Directories..."
find ../alloc -type d -exec chmod 755 {} \;
